-- Generated from C:/Users/16020/Desktop/需求文档/test.docx
-- Run once to import the knowledge bank into t_knowledge

INSERT INTO `t_knowledge` (`question`, `answer`, `status`, `tag`, `del_flag`, `view_count`, `last_view_time`, `add_time`) VALUES
  ('<p>JDK、JRE、JVM三者的区别与联系？</p>', '<p>答案解析：JVM是Java虚拟机，是Java跨平台的核心，负责执行字节码、内存管理、垃圾回收，无编译运行工具；JRE包含JVM+Java核心类库，仅用于运行Java程序；JDK包含JRE+开发编译工具（javac、java、jar），是完整开发环境。层级关系：JDK&gt;JRE&gt;JVM。</p>', 1, 1, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>== 和 equals() 的核心区别？</p>', '<p>答案解析：== 对于基本类型比较数值，引用类型比较内存地址；equals()是Object类方法，原生逻辑等同于==比较地址，String、Integer等类重写后用于比较对象内容。业务中字符串、包装类内容对比必须用equals。</p>', 1, 1, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>String、StringBuilder、StringBuffer 区别？</p>', '<p>答案解析：String是不可变字符序列，拼接会生成新对象，效率低；StringBuffer可变、方法加synchronized，线程安全、效率低，适配多线程拼接；StringBuilder可变、线程不安全、效率最高，单线程拼接首选。</p>', 1, 1, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>重载和重写的区别？</p>', '<p>答案解析：重载是同类中方法名相同、参数列表不同（个数/类型/顺序），编译期多态，与返回值、权限无关；重写是子类覆盖父类非final、非static、非私有方法，方法签名完全一致，权限大于等于父类，运行期多态。</p>', 1, 1, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>抽象类和接口的区别？</p>', '<p>答案解析：抽象类有构造方法、可定义普通变量和普通方法、单继承，侧重代码复用；接口无构造方法、默认public权限、支持多实现，JDK8支持默认/静态方法、JDK9支持私有方法，侧重行为规范和解耦。</p>', 1, 1, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>final、finally、finalize 作用？</p>', '<p>答案解析：final修饰变量不可修改、方法不可重写、类不可继承；finally是异常处理关键字，try-catch后必然执行（除JVM退出），用于资源释放；finalize是Object废弃方法，GC前触发，执行时机不可控，已彻底淘汰。</p>', 1, 1, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Java异常体系结构，受检与非受检异常区别？</p>', '<p>答案解析：顶级父类为Throwable，分为Error（系统级错误，OOM、栈溢出，无需处理）和Exception（程序异常）。受检异常继承Exception，编译期必须捕获或抛出，如IO、SQL异常；非受检异常继承RuntimeException，编译不报错，运行抛出，如空指针、数组越界。</p>', 1, 1, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>序列化与transient关键字作用？</p>', '<p>答案解析：序列化是将Java对象转为字节流，用于网络传输、磁盘持久化；反序列化是字节流还原为对象。transient修饰的成员变量不参与序列化，反序列化后字段为默认空值。</p>', 1, 1, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Java泛型的作用与泛型擦除原理？</p>', '<p>答案解析：泛型作用：编译期类型校验、避免强制类型转换、实现代码通用。核心原理为泛型擦除，泛型仅存在编译阶段，编译后所有泛型信息全部被擦除，运行期统一为原始类型。</p>', 1, 1, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>自动装箱与拆箱原理及坑点？</p>', '<p>答案解析：装箱是基本类型自动转为包装类（int→Integer），拆箱是包装类转基本类型。坑点：Integer缓存-128~127区间对象，该区间内==比较为true，超出区间会新建对象，==比较为false，业务对比必须用equals。</p>', 1, 1, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Java集合核心体系结构？</p>', '<p>答案解析：分为单列集合Collection和双列集合Map。Collection包含List（有序可重复：ArrayList、LinkedList）、Set（无序唯一：HashSet、TreeSet）、Queue队列；Map为键值对结构，键唯一、值可重复，核心实现HashMap、ConcurrentHashMap、TreeMap。</p>', 1, 2, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>ArrayList 和 LinkedList 区别及适用场景？</p>', '<p>答案解析：ArrayList基于动态数组，查询遍历快、中间增删慢，默认容量10，扩容1.5倍，线程不安全，适合查询多、增删少场景；LinkedList基于双向链表，查询慢、首尾增删快，适合频繁插入删除、遍历少的场景。</p>', 1, 2, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>HashMap JDK1.7与1.8底层区别？</p>', '<p>答案解析：1.7底层：数组+链表，头插法扩容，易产生循环链表死循环；1.8底层：数组+链表+红黑树，尾插法避免死循环，链表长度≥8且数组容量≥64树化，链表长度≤6退化为链表，优化哈希扰动算法，查询效率大幅提升。</p>', 1, 2, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>HashMap、HashTable、ConcurrentHashMap 对比？</p>', '<p>答案解析：HashMap线程不安全，允许null键值，高并发易数据覆盖；HashTable全表锁、效率极低、不允许null，已淘汰；ConcurrentHashMap1.7分段锁、1.8采用CAS+synchronized细粒度锁，线程安全、并发性能高，不允许null键。</p>', 1, 2, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>HashSet 如何保证元素唯一性？</p>', '<p>答案解析：HashSet底层完全依托HashMap实现，存入元素作为HashMap的key，value为固定空常量对象。去重逻辑：先判断hashCode是否一致，再比对equals方法，两者均相同判定为重复元素，拒绝存入。</p>', 1, 2, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>TreeSet、TreeMap 排序原理？</p>', '<p>答案解析：底层基于红黑树，可实现自动排序。排序方式两种：自然排序（元素实现Comparable接口重写compareTo）、定制排序（自定义Comparator比较器），未指定排序规则会抛出类型转换异常。</p>', 1, 2, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>fail-fast 快速失败机制原理？</p>', '<p>答案解析：ArrayList、HashMap等非线程安全集合，迭代过程中检测到集合结构被修改（新增/删除元素），会直接抛出ConcurrentModificationException。通过modCount修改计数器与expectedModCount比对实现，避免并发修改异常。</p>', 1, 2, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>LinkedHashMap 有序原理及应用场景？</p>', '<p>答案解析：继承HashMap，底层维护双向链表记录元素插入顺序或访问顺序，保证遍历有序。分为插入有序和访问有序，可基于此实现LRU最近最少淘汰缓存策略，常用于本地缓存实现。</p>', 1, 2, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>ArrayList 线程安全替代方案？</p>', '<p>答案解析：三种方案：1、Vector（全锁，效率低，淘汰）；2、Collections.synchronizedList（方法锁，效率一般）；3、CopyOnWriteArrayList（写时复制，读无锁、写加锁，高并发读多写少场景首选）。</p>', 1, 2, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Iterator 和 ListIterator 区别？</p>', '<p>答案解析：Iterator通用所有集合，仅支持正向遍历、删除元素；ListIterator仅适配List集合，支持正向/反向遍历、新增、修改、删除元素，功能更丰富，针对性更强。</p>', 1, 2, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>进程和线程的核心区别？</p>', '<p>答案解析：进程是操作系统资源分配最小单位，独立内存空间，进程间完全隔离，通信成本极高；线程是CPU调度最小单位，共享所属进程资源，切换成本低、开销小，又称轻量级进程，一个进程可包含多个线程。</p>', 1, 3, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Java线程五大生命周期状态？</p>', '<p>答案解析：新建（New）：创建线程对象未启动；就绪（Runnable）：调用start()，等待CPU调度；运行（Running）：获取CPU时间片执行run方法；阻塞（Blocked）：放弃CPU，分为同步阻塞、等待阻塞、超时阻塞；终止（Terminated）：线程执行完毕或异常结束。</p>', 1, 3, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Java多线程四种实现方式及优劣？</p>', '<p>答案解析：1、继承Thread类：无法继承其他类，局限性大；2、实现Runnable接口：无返回值、无异常抛出，规避单继承限制；3、实现Callable接口：有返回值、可抛异常，配合FutureTask使用；4、线程池创建：企业主流，可复用线程、控制并发、减少开销。</p>', 1, 3, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>synchronized 底层原理及锁升级机制？</p>', '<p>答案解析：synchronized是JVM内置悲观锁，基于对象头MarkWord实现。锁升级顺序：无锁→偏向锁（单线程无竞争）→轻量级锁（少量竞争自旋）→重量级锁（多线程激烈竞争，阻塞等待），锁只能升级不能降级，保障并发性能。</p>', 1, 3, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>synchronized 和 ReentrantLock 区别？</p>', '<p>答案解析：synchronized：自动加解锁、不可中断、无超时、默认非公平、底层JVM实现；ReentrantLock：手动lock/unlock、可中断、可超时、支持公平/非公平锁、多条件唤醒、细粒度控制，高并发性能更优。</p>', 1, 3, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>volatile 关键字三大特性及局限性？</p>', '<p>答案解析：核心特性：保证内存可见性、禁止指令重排序、不保证原子性。局限性：无法解决线程并发安全问题，不能替代锁，仅适用于状态标记、双重校验锁单例等简单场景。</p>', 1, 3, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>CAS 原理、优缺点及ABA问题？</p>', '<p>答案解析：CAS是无锁乐观锁，原理：比较内存值与预期值，一致则更新，不一致则重试。优点：无锁阻塞、并发效率高；缺点：自旋空耗CPU、只能保证单个变量原子性、存在ABA问题。ABA问题解决方案：新增版本号控制（AtomicStampedReference）。</p>', 1, 3, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Java原子类原理及分类？</p>', '<p>答案解析：JUC原子类基于CAS实现无锁原子操作，保证并发安全。分类：基本类型原子类（AtomicInteger）、引用类型、数组类型、字段更新器。适用于简单计数场景，相比锁机制开销更小、效率更高。</p>', 1, 3, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>线程池七大核心参数？</p>', '<p>答案解析：核心线程数、最大线程数、空闲线程存活时间、时间单位、阻塞任务队列、线程工厂、拒绝策略。核心流程：任务优先核心线程→队列排队→新建非核心线程→触发拒绝策略。</p>', 1, 3, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>线程池四种拒绝策略？</p>', '<p>答案解析：1、AbortPolicy：默认策略，直接抛出异常；2、DiscardPolicy：静默丢弃当前任务，无异常；3、DiscardOldestPolicy：丢弃队列最久任务，重试提交；4、CallerRunsPolicy：由调用者线程执行任务，不丢弃不报错。</p>', 1, 3, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>为什么禁止使用Executors创建线程池？</p>', '<p>答案解析：Executors工具类创建的线程池存在隐患：FixedThreadPool、SingleThreadPool队列无界，任务堆积引发OOM；CachedThreadPool最大线程数无限制，大量线程创建导致CPU爆满、线程溢出。企业必须手动通过ThreadPoolExecutor创建。</p>', 1, 3, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>sleep() 和 wait() 核心区别？</p>', '<p>答案解析：sleep是Thread静态方法，休眠指定时间，不释放锁资源；wait是Object方法，必须在同步代码块执行，主动释放锁，可被notify唤醒；sleep属于线程状态超时阻塞，wait属于主动等待阻塞。</p>', 1, 3, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>notify() 和 notifyAll() 区别？</p>', '<p>答案解析：notify()随机唤醒一个等待线程，可能导致部分线程永久等待；notifyAll()唤醒所有等待线程，全部进入锁竞争状态，业务开发中优先使用notifyAll避免线程饿死。</p>', 1, 3, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>ThreadLocal 原理、作用及内存泄漏问题？</p>', '<p>答案解析：原理：线程内部维护ThreadLocalMap，以ThreadLocal为key、自定义数据为value，实现线程数据隔离。作用：存储线程私有数据，实现参数全局透传。内存泄漏：key弱引用、value强引用，线程不销毁则value无法释放，需手动remove清除。</p>', 1, 3, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>死锁产生的四个必要条件及解决方案？</p>', '<p>答案解析：四大条件：互斥条件、请求保持、不可剥夺、循环等待。解决思路：破坏任意一个条件，核心方案：统一锁获取顺序、设置锁超时、避免嵌套锁。</p>', 1, 3, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>CountDownLatch、CyclicBarrier、Semaphore 区别？</p>', '<p>答案解析：CountDownLatch：倒计时计数器，一次性使用，主线程等待子线程完成；CyclicBarrier：循环栅栏，可重复使用，线程互相等待集齐后统一执行；Semaphore：信号量，控制并发线程数量，用于限流、资源抢占。</p>', 1, 3, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>乐观锁与悲观锁区别及适用场景？</p>', '<p>答案解析：悲观锁默认并发冲突，全程加锁阻塞，synchronized、数据库行锁属于悲观锁，适合并发冲突多场景；乐观锁默认无冲突，版本号/CAS校验，无锁阻塞，适合读多写少、冲突少场景。</p>', 1, 3, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>CopyOnWriteArrayList 读写分离原理？</p>', '<p>答案解析：写时复制机制：读操作直接访问原数组，无锁高效；写操作加锁，复制新数组完成修改，再替换原数组。读写分离，解决并发读性能问题，适合读多写少场景，缺点是写操作内存开销大、有数据弱一致性。</p>', 1, 3, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>并发编程中指令重排序是什么？如何禁止？</p>', '<p>答案解析：CPU和编译器为提升执行效率，会打乱代码执行顺序，保证单线程结果不变，但多线程会出现数据错乱。禁止方式：volatile关键字内存屏障、synchronized锁、final关键字。</p>', 1, 3, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>多线程变量可见性问题产生原因？</p>', '<p>答案解析：Java内存模型中，线程会将主内存变量拷贝到本地工作内存缓存，多线程各自缓存变量，彼此不可见，导致主内存数据更新后其他线程无法感知，volatile可强制刷新主内存、保证可见性。</p>', 1, 3, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>JVM运行时数据区详细划分？</p>', '<p>答案解析：线程私有区（随线程创建销毁）：程序计数器（无OOM，记录字节码行号）、虚拟机栈（存储栈帧、局部变量，栈溢出）、本地方法栈（执行native方法）；线程共享区（全局共享）：堆内存（对象实例、GC核心区）、元空间（类信息、常量、静态变量，JDK8替换永久代）。</p>', 1, 4, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>程序计数器为什么是唯一无OOM区域？</p>', '<p>答案解析：程序计数器仅记录当前线程执行的字节码地址，数据量极小、固定占用内存，无内存溢出场景，是JVM唯一不会抛出OOM的内存区域。</p>', 1, 4, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>堆内存结构与分代思想？</p>', '<p>答案解析：堆内存分为新生代、老年代。新生代占堆1/3，分为Eden区、两个Survivor区，存放短期存活对象；老年代占堆2/3，存放长期存活、大对象。分代目的：针对性GC，新生代对象消亡快、高频轻量GC，老年代对象稳定、低频重量级GC，提升回收效率。</p>', 1, 4, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>对象创建流程（JVM层面）？</p>', '<p>答案解析：类加载校验→分配内存（指针碰撞/空闲列表）→初始化默认值→设置对象头（哈希码、锁状态、GC分代年龄）→执行构造方法→对象创建完成。</p>', 1, 4, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>对象在内存中的布局？</p>', '<p>答案解析：分为三部分：对象头（MarkWord+类型指针，存储锁、GC、哈希信息）、实例数据（成员变量数据）、对齐填充（保证内存8字节对齐，提升访问效率）。</p>', 1, 4, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>JVM判断对象可回收的两种方式？</p>', '<p>答案解析：1、引用计数法：对象被引用计数+1，失效-1，计数0可回收，弊端：无法解决循环引用；2、可达性分析法（主流）：以GC Roots为起点，无引用链可达的对象判定为垃圾对象，可回收。</p>', 1, 4, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>GC Roots 包含哪些对象？</p>', '<p>答案解析：虚拟机栈中局部变量引用对象、本地方法栈JNI引用对象、方法区静态变量/常量引用对象、活跃线程对象、系统类加载器加载对象。</p>', 1, 4, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>四种引用类型及GC回收规则？</p>', '<p>答案解析：强引用：默认引用，永不回收；软引用：内存不足时回收，适合缓存；弱引用：下次GC必回收；虚引用：无实际引用作用，仅用于监控GC回收时机。</p>', 1, 4, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Minor GC、Major GC、Full GC 区别？</p>', '<p>答案解析：Minor GC：新生代专属回收，频率高、速度快、STW短；Major GC：老年代回收，频率低、耗时久；Full GC：整堆+元空间全量回收，STW最长、严重影响性能，生产环境需尽量避免。</p>', 1, 4, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>常见垃圾收集器特点？</p>', '<p>答案解析：新生代：Serial单线程回收、Parallel并行吞吐量优先、ParNew适配CMS；老年代：CMS并发低延迟；整堆：G1分区回收、ZGC超低延迟、Shenandoah低延迟，高并发低延迟业务首选ZGC/G1。</p>', 1, 4, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>CMS垃圾回收流程与弊端？</p>', '<p>答案解析：流程：初始标记→并发标记→重新标记→并发清除。弊端：产生内存碎片、浮动垃圾、并发阶段占用CPU资源，无法处理极端大对象。</p>', 1, 4, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>G1收集器核心原理与优势？</p>', '<p>答案解析：将堆内存划分为多个大小相等的Region分区，可单独回收新生代/老年代分区，支持可预测的停顿时间，兼顾吞吐量和低延迟，解决CMS内存碎片问题，是JDK9+默认收集器。</p>', 1, 4, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>JVM类加载全过程？</p>', '<p>答案解析：加载（读取class字节码）→验证（校验字节码合法性）→准备（静态变量默认赋值）→解析（符号引用转直接引用）→初始化（静态代码块、静态变量赋值）。</p>', 1, 4, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>双亲委派模型原理与作用？</p>', '<p>答案解析：类加载器层级：启动类加载器→扩展类加载器→应用类加载器。加载类时层层向上委托，上级无法加载再由下级加载。作用：保证核心类安全、避免类重复加载、统一类加载规范。</p>', 1, 4, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>什么是类卸载？卸载条件？</p>', '<p>答案解析：方法区的无用类可被卸载回收。条件：类所有实例被回收、类加载器被回收、Class对象无引用，满足三者才可卸载，JVM很少主动卸载类。</p>', 1, 4, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>OOM内存溢出常见场景与排查？</p>', '<p>答案解析：常见场景：堆内存溢出（对象过多不释放）、元空间溢出（动态生成类过多）、栈溢出（递归死循环）、直接内存溢出。排查方式：导出dump文件，通过MAT、JProfiler分析大对象、内存泄漏点位。</p>', 1, 4, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>JVM调优核心目标与常用参数？</p>', '<p>答案解析：调优目标：减少Full GC、降低STW、提升吞吐量、控制内存占用。常用参数：-Xms初始堆、-Xmx最大堆、-Xss栈大小、-XX:+UseG1GC开启G1、-XX:MaxMetaspaceSize元空间上限。</p>', 1, 4, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>逃逸分析的作用？</p>', '<p>答案解析：JVM编译优化手段，分析对象是否逃逸出方法/线程。未逃逸对象可进行栈上分配、标量替换、同步消除，减少堆对象创建，降低GC压力，提升运行效率。</p>', 1, 4, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>STW是什么？哪些GC会触发STW？</p>', '<p>答案解析：STW即Stop-The-World，GC执行时暂停所有用户线程，仅保留GC线程工作。所有GC都会触发STW，Minor GC短STW，Full GC长STW，是应用卡顿的核心原因。</p>', 1, 4, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>内存泄漏与内存溢出区别？</p>', '<p>答案解析：内存泄漏：无用对象持续持有引用，无法被GC回收，内存缓慢占用；内存溢出：内存占用达到上限，无法分配新内存，直接报错。长期内存泄漏最终会导致内存溢出。</p>', 1, 4, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Spring两大核心思想？IOC、AOP原理？</p>', '<p>答案解析：核心：IOC控制反转、AOP面向切面编程。IOC：将对象创建、依赖注入、生命周期管理交由Spring容器，反转程序控制权，彻底解耦；AOP：基于动态代理，不修改源码的前提下对方法增强，实现日志、事务、权限等通用横切逻辑。</p>', 1, 5, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Spring Bean完整生命周期？</p>', '<p>答案解析：实例化对象→填充属性依赖→Bean前置处理→初始化方法（init-method）→Bean后置处理→Bean就绪可用→容器关闭执行销毁方法。</p>', 1, 5, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Spring Bean五种作用域？</p>', '<p>答案解析：singleton（单例，容器全局唯一，默认）、prototype（多例，每次获取新建对象）、request（单次请求有效）、session（单次会话有效）、application（全局应用有效）。</p>', 1, 5, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Spring三种依赖注入方式及推荐方案？</p>', '<p>答案解析：字段注入、setter注入、构造器注入。Spring官方推荐构造器注入，优势：保证依赖不可变、对象初始化完整、有效避免循环依赖、方便单元测试。</p>', 1, 5, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Spring AOP核心术语与五种通知？</p>', '<p>答案解析：核心术语：切点、连接点、切面、通知、引入。五种通知：前置通知、后置返回通知、后置异常通知、最终通知、环绕通知（功能最强，可控制方法执行）。</p>', 1, 5, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Spring AOP JDK动态代理与CGLIB代理区别？</p>', '<p>答案解析：JDK代理：基于接口实现，仅能代理接口实现类；CGLIB代理：基于子类继承，无需接口，可代理普通类。Spring默认：有接口用JDK代理，无接口用CGLIB。</p>', 1, 5, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Spring循环依赖产生原因及解决方案？</p>', '<p>答案解析：原因：两个Bean互相依赖注入。Spring通过三级缓存解决单例Setter/字段注入循环依赖，无法解决构造器注入、多例Bean循环依赖。三级缓存分别存储半成品Bean、提前引用、代理对象。</p>', 1, 5, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Spring事务四大传播机制、七大隔离级别？</p>', '<p>答案解析：核心传播机制：REQUIRED（默认，有则加入、无则新建）、SUPPORTS、MANDATORY、REQUIRES_NEW（新建独立事务）；隔离级别：DEFAULT、读未提交、读已提交、可重复读、串行化等，解决脏读、不可重复读、幻读问题。</p>', 1, 5, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Spring事务失效的常见场景？</p>', '<p>答案解析：1、方法非public；2、内部调用本类事务方法；3、异常被try-catch捕获未抛出；4、传播机制配置不当；5、数据库引擎不支持事务（MyISAM）；6、多线程事务失效。</p>', 1, 5, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Spring MVC完整工作流程？</p>', '<p>答案解析：客户端请求→DispatcherServlet前端控制器→HandlerMapping匹配处理器→HandlerAdapter执行控制器方法→业务处理返回ModelAndView→视图解析器渲染视图→响应客户端。</p>', 1, 5, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>过滤器和拦截器区别？</p>', '<p>答案解析：过滤器（Filter）：Servlet原生组件，全局拦截所有请求，运行在Spring容器外，优先执行；拦截器（Interceptor）：Spring MVC组件，仅拦截控制器请求，可获取Spring上下文，后置处理更灵活。</p>', 1, 5, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>SpringBoot自动配置原理？</p>', '<p>答案解析：核心注解@EnableAutoConfiguration，通过SPI机制读取META-INF/spring.factories配置文件，根据项目依赖Jar包自动装配对应组件，无需手动配置，实现开箱即用。</p>', 1, 5, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>SpringBoot Starter机制作用？</p>', '<p>答案解析：Starter是SpringBoot的依赖封装组件，整合依赖Jar包和自动配置类，开发者只需引入对应starter依赖，即可自动完成组件初始化、配置加载，简化项目搭建，规避版本冲突。</p>', 1, 5, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>yml和properties配置文件区别？</p>', '<p>答案解析：properties格式简单、优先级高、无层级；yml树形结构、可读性强、支持多环境配置、语法严格。SpringBoot中同名配置，properties优先级高于yml。</p>', 1, 5, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>SpringBoot全局异常处理方案？</p>', '<p>答案解析：通过@RestControllerAdvice全局异常拦截，配合@ExceptionHandler捕获指定异常，统一封装返回结果，避免前端接收原生异常信息，统一接口返回格式。</p>', 1, 5, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>SpringBoot跨域解决方案？</p>', '<p>答案解析：三种方案：1、注解@CrossOrigin局部跨域；2、实现WebMvcConfigurer全局跨域配置；3、自定义CorsFilter过滤器统一处理，企业常用全局配置方式。</p>', 1, 5, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>SpringBoot启动流程？</p>', '<p>答案解析：启动入口main方法→初始化SpringApplication→加载配置、环境变量→扫描Bean、自动配置→刷新容器、初始化组件→启动内嵌Tomcat→项目启动完成。</p>', 1, 5, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Spring Bean的循环依赖为什么构造器注入无法解决？</p>', '<p>答案解析：构造器注入需要在对象实例化时完成依赖注入，此时对象还未创建完成，无法存入三级缓存，导致循环依赖卡死；Setter/字段注入先实例化空对象，存入缓存后再注入依赖，可解决循环依赖。</p>', 1, 5, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Spring中事务的失效传播场景？</p>', '<p>答案解析：外层无事务、内层REQUIRES_NEW新建事务互不影响；外层事务提交后内层独立事务才执行；嵌套事务异常可单独回滚，不影响外层事务，精准控制事务粒度。</p>', 1, 5, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Spring MVC参数绑定原理？</p>', '<p>答案解析：通过HandlerAdapter调用参数解析器，根据请求参数类型、注解（@RequestParam、@RequestBody），自动将请求数据封装为Java对象，完成类型转换、参数校验，实现参数自动绑定。</p>', 1, 5, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>MyBatis核心工作流程？</p>', '<p>答案解析：加载全局配置文件→解析映射文件→构建SqlSessionFactory→创建SqlSession会话→获取Mapper代理对象→执行SQL语句→封装结果集→关闭SqlSession释放资源。</p>', 1, 6, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>#{} 和 ${} 的核心区别与使用场景？</p>', '<p>答案解析：#{}是预编译占位符，自动拼接引号，防止SQL注入，安全常用；${}是字符串直接拼接，存在SQL注入风险，无需预编译，仅用于动态表名、字段名、排序字段场景。</p>', 1, 6, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>MyBatis一级缓存和二级缓存区别？</p>', '<p>答案解析：一级缓存：SqlSession会话级别，默认开启，会话内查询缓存生效，关闭/清空会话即失效；二级缓存：Mapper命名空间级别，跨会话全局缓存，需手动开启配置，适合高频查询、低频更新场景。</p>', 1, 6, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>MyBatis动态SQL常用标签及作用？</p>', '<p>答案解析：if：条件判断；where：自动去除多余and/or；foreach：遍历集合批量操作；choose/when：多条件分支；set：动态更新字段，解决空值更新问题，大幅提升SQL灵活性。</p>', 1, 6, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>MyBatis分页原理与分页插件使用？</p>', '<p>答案解析：原生MyBatis无分页功能，仅支持内存分页（效率低）；企业通用PageHelper分页插件，基于MyBatis拦截器原理，拦截SQL自动拼接limit语句，实现物理分页，性能优异。</p>', 1, 6, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>MyBatis延迟加载原理及配置？</p>', '<p>答案解析：针对关联查询，默认按需加载，查询主表时不加载关联表数据，访问关联属性时才执行SQL查询，减少无效SQL查询、提升性能，适合多表关联场景。</p>', 1, 6, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>MyBatis主键回填实现方式？</p>', '<p>答案解析：MySQL自增主键：useGeneratedKeys=true获取自增ID；UUID主键：通过selectKey标签提前生成主键并回填，新增数据后可直接获取主键值。</p>', 1, 6, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>MyBatis批量插入优缺点？</p>', '<p>答案解析：通过foreach拼接values实现批量插入，减少数据库连接次数、提升插入效率；缺点：数据量过大时SQL过长，超出数据库限制，需分批批量插入。</p>', 1, 6, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>MyBatis-Plus核心优势与常用注解？</p>', '<p>答案解析：优势：简化CRUD、无需手写SQL、内置分页、条件构造器、主键策略、自动填充。常用注解：@TableName、@TableId、@TableField、@Version乐观锁、@TableLogic逻辑删除。</p>', 1, 6, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>MyBatis-Plus条件构造器 QueryWrapper、LambdaQueryWrapper区别？</p>', '<p>答案解析：QueryWrapper基于字符串字段名，易写错；LambdaQueryWrapper基于Lambda表达式，通过实体属性匹配字段，无硬编码、零拼写错误，企业开发首选。</p>', 1, 6, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>MySQL事务ACID四大特性？</p>', '<p>答案解析：原子性：事务不可分割，要么全成功要么全回滚；一致性：事务前后数据完整性、约束一致性不变；隔离性：多并发事务互相隔离、互不干扰；持久性：事务提交后数据永久落地，断电不丢失。</p>', 1, 7, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>MySQL四大事务隔离级别及问题？</p>', '<p>答案解析：1、读未提交：脏读、不可重复读、幻读全存在；2、读已提交：解决脏读，剩余两种问题；3、可重复读（InnoDB默认）：解决脏读、不可重复读，存在幻读；4、串行化：完全解决问题，性能最低。</p>', 1, 7, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>脏读、不可重复读、幻读区别？</p>', '<p>答案解析：脏读：读取到其他事务未提交的脏数据；不可重复读：同一事务两次查询结果不一致（数据修改）；幻读：同一事务两次查询条数不一致（数据新增/删除）。</p>', 1, 7, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>InnoDB与MyISAM引擎核心区别？</p>', '<p>答案解析：InnoDB支持事务、行锁、外键、MVCC、崩溃恢复，读写均衡，默认引擎；MyISAM不支持事务、仅表锁、无外键、崩溃易丢数据，查询快，已淘汰。</p>', 1, 7, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>MySQL索引底层B+树优势？</p>', '<p>答案解析：层级少、磁盘IO次数少、查询效率高；所有数据存储在叶子节点，全覆盖查询；叶子节点有序链表，支持高效范围查询、排序查询，适配数据库所有查询场景。</p>', 1, 7, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>聚簇索引与非聚簇索引区别？</p>', '<p>答案解析：聚簇索引即主键索引，叶子节点存储完整行数据；非聚簇索引（二级索引）叶子节点存储主键值，查询数据需要回表通过主键查询完整数据。</p>', 1, 7, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>覆盖索引原理及作用？</p>', '<p>答案解析：查询字段全部包含在索引中，无需回表查询原始数据，避免回表IO开销，大幅提升查询效率，是MySQL最优索引优化方案。</p>', 1, 7, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>联合索引最左前缀原则？</p>', '<p>答案解析：联合索引遵循最左匹配，必须匹配左侧首个字段，索引才会生效，跳过左侧字段、乱序匹配都会导致索引失效，设计索引需优先高频查询字段。</p>', 1, 7, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>MySQL索引失效常见场景？</p>', '<p>答案解析：like %前缀模糊查询、索引列参与运算/函数、隐式类型转换、or无全索引、not in/not exists、order by字段无索引、违反最左前缀原则。</p>', 1, 7, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>MySQL行锁与表锁区别？</p>', '<p>答案解析：表锁锁定整张表，开销小、粒度大、并发低；行锁锁定单行数据，粒度小、并发高、仅InnoDB支持；行锁基于索引生效，无索引会降级为表锁。</p>', 1, 7, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>MVCC多版本并发控制原理？</p>', '<p>答案解析：InnoDB无锁读核心机制，基于undo日志版本链+ReadView，为事务生成数据快照，实现读写不阻塞、解决并发读问题，支撑可重复读隔离级别。</p>', 1, 7, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>redo日志与undo日志作用？</p>', '<p>答案解析：redo日志：重做日志，保证事务持久性，崩溃恢复数据；undo日志：回滚日志，保证原子性、实现MVCC数据版本快照。</p>', 1, 7, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>MySQL慢查询优化通用思路？</p>', '<p>答案解析：开启慢查询日志定位慢SQL、explain分析执行计划、优化索引、避免索引失效、优化关联查询、分页优化、避免大事务、分库分表、读写分离。</p>', 1, 7, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>explain执行计划核心字段含义？</p>', '<p>答案解析：type：查询类型（all全表扫描最差、ref最优）；key：实际使用索引；rows：扫描行数；Extra：额外信息（Using filesort文件排序、Using temporary临时表均需优化）。</p>', 1, 7, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>数据库悲观锁与乐观锁实现？</p>', '<p>答案解析：悲观锁：select ... for update，加行锁阻塞并发；乐观锁：基于版本号/时间戳，更新时校验版本，无锁并发，适合读多写少场景。</p>', 1, 7, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>MySQL主从复制原理？</p>', '<p>答案解析：主库记录binlog日志，从库IO线程拉取日志、写入本地relay日志，从库SQL线程重放日志，同步主库数据，实现读写分离、数据备份。</p>', 1, 7, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>分库分表场景与分片策略？</p>', '<p>答案解析：单表超千万、QPS过高需分表，单库压力过大需分库。策略：水平分表、垂直分表、水平分库、垂直分库，常用Sharding-JDBC实现。</p>', 1, 7, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Redis五种基础数据结构及场景？</p>', '<p>答案解析：String：缓存、计数器、分布式ID；List：消息队列、有序列表；Set：去重、交集、好友列表；Hash：用户对象、购物车；ZSet：排行榜、延时队列、权重排序。</p>', 1, 7, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Redis过期删除策略？</p>', '<p>答案解析：惰性删除：访问时判断过期删除，节省CPU；定期删除：随机抽样清理过期key，平衡内存与CPU，两者结合实现高效过期清理。</p>', 1, 7, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Redis内存淘汰策略？</p>', '<p>答案解析：8种策略，核心4种：volatile-lru淘汰过期最少使用、allkeys-lru全局最少使用、volatile-ttl淘汰即将过期、noeviction默认不淘汰、直接报错。</p>', 1, 7, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>缓存穿透、击穿、雪崩区别及解决方案？</p>', '<p>答案解析：穿透：查询不存在数据，方案：布隆过滤器、空值缓存、接口校验；击穿：热点key过期，方案：互斥锁、永不过期；雪崩：大量key同时过期/集群宕机，方案：过期时间随机、集群、熔断降级。</p>', 1, 7, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Redis分布式锁实现原理？</p>', '<p>答案解析：基于set nx ex命令，加锁：唯一key+过期时间；解锁：Lua脚本原子删除，解决超期释放、误删问题，适配分布式集群锁场景。</p>', 1, 7, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Redis持久化RDB与AOF区别？</p>', '<p>答案解析：RDB快照持久化，压缩文件、恢复快、可能丢数据；AOF日志追加持久化、数据完整、恢复慢、文件大，生产环境推荐RDB+AOF混合持久化。</p>', 1, 7, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Redis集群模式对比？</p>', '<p>答案解析：单机：简单无高可用；主从：数据备份、无故障转移；哨兵：监控、自动故障转移、高可用；集群：分片存储、横向扩容、海量数据支撑。</p>', 1, 7, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>缓存一致性问题解决方案？</p>', '<p>答案解析：更新策略：先更数据库、后删缓存；过期兜底：缓存自动过期；异步兜底：消息队列异步更新，保障数据库与缓存数据最终一致。</p>', 1, 7, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Redis为什么快？</p>', '<p>答案解析：纯内存操作、单线程无锁竞争、IO多路复用、数据结构高效、协议简单，避免线程切换开销，吞吐量极高。</p>', 1, 7, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>MySQL死锁产生原因与解决？</p>', '<p>答案解析：多线程互相持有对方锁、等待对方资源，形成循环等待。解决：统一锁顺序、缩短事务执行时间、避免嵌套锁、数据库超时检测。</p>', 1, 7, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>大事务危害与优化？</p>', '<p>答案解析：危害：锁持有时间长、并发低、回滚成本高、产生死锁、主从延迟。优化：拆分大事务、减少事务内查询、避免循环操作、精简事务逻辑。</p>', 1, 7, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>SQL慢查询常见优化手段？</p>', '<p>答案解析：避免select *、优化limit分页、禁止in大集合、避免函数索引、合理使用联合索引、拆分复杂SQL、避免笛卡尔积、优化join关联条件。</p>', 1, 7, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>读写分离原理与实现？</p>', '<p>答案解析：主库负责写操作、从库负责读操作，分担数据库压力。实现方式：Sharding-JDBC代码层读写分离、中间件MyCat代理层读写分离，解决单库读写压力瓶颈。</p>', 1, 7, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>单体架构与微服务架构区别？</p>', '<p>答案解析：单体架构：代码耦合、部署简单、扩容困难、迭代慢、适合小型项目；微服务：业务拆分、独立部署、独立扩容、高可用、迭代快、适配大型分布式项目，运维和分布式复杂度更高。</p>', 1, 8, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>微服务核心优缺点？</p>', '<p>答案解析：优点：服务解耦、独立迭代、弹性扩容、技术栈灵活、故障隔离；缺点：分布式事务、服务调用、运维复杂、网络开销大、需要注册中心、网关、监控等中间件支撑。</p>', 1, 8, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>SpringCloud核心组件全家桶？</p>', '<p>答案解析：注册中心：Nacos；网关：Spring Cloud Gateway；服务调用：OpenFeign；负载均衡：Ribbon；熔断降级：Sentinel；配置中心：Nacos；链路追踪：SkyWalking；消息队列：RabbitMQ/Kafka。</p>', 1, 8, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Nacos注册中心原理与优势？</p>', '<p>答案解析：Nacos兼具注册中心+配置中心功能，AP架构支持服务注册发现，CP架构支持配置持久化。优势：轻量易用、兼容SpringCloud、支持动态配置刷新、自带健康检查、集群高可用，替代Eureka+Config，简化微服务架构组件。</p>', 1, 8, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Nacos服务健康检查机制？</p>', '<p>答案解析：分为客户端主动上报、服务端被动检测。客户端定时发送心跳包（默认5s），服务端15s未接收标记不健康、30s未接收直接剔除实例。支持临时实例（心跳维持，宕机自动剔除）、持久实例（手动上下线）。</p>', 1, 8, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Spring Cloud Gateway 核心原理与优势？</p>', '<p>答案解析：基于Netty+WebFlux实现响应式网关，核心流程：路由匹配→断言校验→过滤器处理→转发请求。优势：性能优于Zuul、支持动态路由、限流、熔断、跨域、全局拦截，适配高并发微服务网关场景。</p>', 1, 8, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>网关过滤器的两种类型及执行顺序？</p>', '<p>答案解析：分为全局过滤器GlobalFilter、局部路由过滤器。执行顺序：前置过滤器PreFilter（请求转发前执行，做鉴权、限流、参数校验）→路由转发→后置过滤器PostFilter（响应返回前执行，做日志、结果封装）。</p>', 1, 8, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>OpenFeign原理及超时配置？</p>', '<p>答案解析：OpenFeign是声明式远程调用组件，基于动态代理封装HTTP请求，无需手动拼接URL、封装参数，简化微服务调用。默认集成Ribbon负载均衡，可自定义连接超时、读取超时，适配服务间同步调用。</p>', 1, 8, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Ribbon负载均衡策略与重试机制？</p>', '<p>答案解析：常用策略：轮询、随机、加权轮询、响应时间权重。支持失败重试，调用失败自动切换可用实例，提升服务调用稳定性，适配集群多实例负载分发场景。</p>', 1, 8, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Sentinel熔断降级、限流核心能力？</p>', '<p>答案解析：限流：QPS限流、线程数限流、热点参数限流，防止流量打垮服务；熔断：服务异常率过高自动熔断，避免级联故障；降级：非核心业务兜底返回，保障核心业务可用，实现微服务高可用防护。</p>', 1, 8, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Sentinel与Hystrix区别？</p>', '<p>答案解析：Hystrix功能单一、停止更新、仅支持熔断隔离；Sentinel轻量、实时监控、支持限流+熔断+降级+热点防护、控制台可视化配置、动态规则生效，是目前微服务主流防护组件。</p>', 1, 8, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>微服务雪崩、级联故障如何解决？</p>', '<p>答案解析：核心解决方案：服务熔断、服务降级、接口限流、超时控制、线程池隔离、集群部署、故障隔离，阻断故障向上传递，避免单一服务故障导致整体架构瘫痪。</p>', 1, 8, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>分布式事务问题产生原因？</p>', '<p>答案解析：微服务拆分后，单次业务跨多个服务、多个数据库，本地事务无法保证全局ACID，出现部分服务提交、部分服务回滚，导致数据不一致，是微服务核心痛点。</p>', 1, 8, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>分布式事务常见解决方案？</p>', '<p>答案解析：常见方案：本地消息表、可靠消息队列、TCC柔性事务、SAGA长事务、Seata AT事务。企业主流：Seata AT无侵入、适配绝大多数业务，高一致性场景用TCC。</p>', 1, 8, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Seata AT模式工作原理？</p>', '<p>答案解析：基于两阶段提交，一阶段执行业务SQL、记录undo日志、不提交事务；二阶段成功批量提交、删除日志，失败根据undo日志回滚数据，无代码侵入，适配微服务分布式事务。</p>', 1, 8, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>微服务接口幂等性解决方案？</p>', '<p>答案解析：接口重复调用不产生脏数据。方案：唯一订单号幂等、Token令牌、数据库唯一索引、状态机控制、Redis分布式锁，解决重试、重复提交问题。</p>', 1, 8, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>微服务监控链路追踪作用？</p>', '<p>答案解析：基于SkyWalking/Sleuth+Zipkin，追踪请求全链路调用日志、耗时、异常点位，快速定位跨服务调用卡顿、报错、超时问题，解决微服务排查难、链路复杂问题。</p>', 1, 8, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>配置中心核心作用？</p>', '<p>答案解析：统一管理全环境配置、动态刷新配置、无需重启服务、区分环境配置、权限管控、配置版本回溯，解决传统本地配置文件分散、修改繁琐、重启生效问题。</p>', 1, 8, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>微服务高可用架构设计？</p>', '<p>答案解析：多实例集群部署、注册中心集群、网关高可用、熔断降级限流、超时重试、故障隔离、读写分离、异地多活、定时监控告警，全方位保障服务不宕机、业务不中断。</p>', 1, 8, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>单体架构拆分为微服务的拆分原则？</p>', '<p>答案解析：按业务域垂直拆分、高内聚低耦合、单一职责、避免过度拆分、核心业务独立部署、公共服务下沉（用户、文件、支付），保证服务边界清晰、便于独立迭代扩容。</p>', 1, 8, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>常用消息队列选型对比（RabbitMQ/Kafka/RocketMQ）？</p>', '<p>答案解析：RabbitMQ：可靠性高、事务完善、适合金融业务、吞吐量一般；Kafka：超高吞吐量、低延迟、适合日志、大数据流式处理；RocketMQ：阿里开源、高可靠、高吞吐、兼顾事务与性能，业务系统首选。</p>', 1, 9, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>消息队列核心作用？</p>', '<p>答案解析：四大核心作用：解耦（服务异步通信，减少代码耦合）、削峰填谷（瞬时流量缓冲，保护后端服务）、异步处理（非核心业务异步化，提升接口响应速度）、流量规整（统一消费节奏）。</p>', 1, 9, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>消息队列如何保证消息不丢失？</p>', '<p>答案解析：生产者：开启确认机制、重试机制；服务端：持久化消息、集群副本；消费者：手动ACK确认、消费成功再签收，三步闭环彻底杜绝消息丢失。</p>', 1, 9, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>消息重复消费问题及幂等解决方案？</p>', '<p>答案解析：网络超时、ACK丢失会导致消息重发。解决方案：消息唯一ID做幂等校验、业务状态机判断、Redis记录消费记录、数据库唯一索引，保证重复消费不脏数据。</p>', 1, 9, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>消息积压原因及解决方案？</p>', '<p>答案解析：原因：消费者消费速度慢、消费者宕机、业务阻塞、消息异常重试堆积。方案：排查消费异常、扩容消费者节点、批量消费、优化消费逻辑、死信队列兜底、临时分流处理。</p>', 1, 9, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>死信队列作用与使用场景？</p>', '<p>答案解析：消息超时未消费、消费失败次数过多、消息被拒绝，会转入死信队列。作用：兜底存储异常消息、避免无限重试、便于人工排查修复，保证业务不阻塞。</p>', 1, 9, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>延时队列实现原理与业务场景？</p>', '<p>答案解析：基于消息过期时间+死信队列实现延时效果。场景：订单超时取消、超时未支付关闭、定时通知、延时任务处理，替代定时任务，精度更高、性能更好。</p>', 1, 9, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>消息事务消息原理？</p>', '<p>答案解析：半消息机制：先发送半消息、本地事务执行、根据事务结果提交/回滚消息，解决本地事务与消息发送一致性问题，适配下单、支付等强一致业务。</p>', 1, 9, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>同步消息与异步消息区别？</p>', '<p>答案解析：同步消息：生产者发送后阻塞等待消费结果，一致性高、响应慢；异步消息：发送后立即返回，不阻塞主线程、响应快、吞吐量高，主流业务均采用异步消息。</p>', 1, 9, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>消息队列如何保证消息有序性？</p>', '<p>答案解析：全局有序：单队列单消费者；局部有序：按业务维度哈希分片，相同业务消息进入同一分区，保证分区内有序，兼顾有序性与并发吞吐量。</p>', 1, 9, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Elasticsearch核心作用与适用场景？</p>', '<p>答案解析：分布式全文检索引擎，基于Lucene封装。场景：全文模糊搜索、日志检索、商品搜索、海量数据实时查询、数据聚合统计，弥补数据库模糊查询效率低、无法分词检索短板。</p>', 1, 10, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>ES核心概念：索引、文档、分片、副本？</p>', '<p>答案解析：索引：类比数据库库表；文档：单条JSON数据，类比行数据；分片：数据拆分存储，解决海量数据存储；副本：分片备份，保证高可用，主分片负责写入，副本负责读取、故障转移。</p>', 1, 10, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>ES倒排索引原理？</p>', '<p>答案解析：正向索引：文档→关键词；倒排索引：关键词→文档列表。分词后建立词条与文档映射关系，检索时通过词条快速匹配对应文档，实现毫秒级全文检索，是ES高效查询核心。</p>', 1, 10, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>ES分词器原理与常用分词器？</p>', '<p>答案解析：分词器将文本拆分为独立词条，用于索引和检索。常用：standard默认分词、ik_max_word细粒度中文分词、ik_smart粗粒度分词，中文检索必须使用IK分词器。</p>', 1, 10, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>ES精准查询与模糊查询区别？</p>', '<p>答案解析：精准查询（term/match_phrase）：完全匹配词条、不拆分文本、效率高；模糊查询（match）：自动分词匹配、支持模糊检索、适配全文搜索场景，精准查询性能远优于模糊查询。</p>', 1, 10, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>ES深分页问题及解决方案？</p>', '<p>答案解析：from+size深分页会加载大量数据排序，性能极差。解决方案：scroll滚动分页（海量数据导出）、search_after游标分页（精准深分页查询），规避深分页性能瓶颈。</p>', 1, 10, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>ES聚合查询作用与常用聚合？</p>', '<p>答案解析：实现数据统计分析，无需查数据库。常用：桶聚合（分组统计）、指标聚合（求和、平均值、最大值、计数），适配后台数据报表、统计分析场景。</p>', 1, 10, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>ES读写分离机制？</p>', '<p>答案解析：写入操作默认走主分片，同步至副本分片；查询请求均衡分发主、副分片，读写分离分担查询压力，提升集群查询吞吐量。</p>', 1, 10, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>ES数据同步MySQL方案？</p>', '<p>答案解析：主流方案：Logstash同步、Canal监听binlog增量同步。Canal方案无侵入、性能高、实时性强，监听MySQL日志增量同步数据，保证ES与数据库数据一致。</p>', 1, 10, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>ES集群高可用保障？</p>', '<p>答案解析：分片副本冗余、集群节点故障自动转移、主分片自动选举、数据持久化、集群健康监控，单节点宕机不影响整体服务，保障检索业务高可用。</p>', 1, 10, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Vue2与Vue3核心区别？</p>', '<p>答案解析：Vue2：选项式API、Object.defineProperty监听数据、单根节点、性能一般；Vue3：组合式API、Proxy代理监听、支持多根节点、打包体积更小、渲染速度更快、支持TS、逻辑复用更灵活。</p>', 1, 11, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Vue双向绑定原理？</p>', '<p>答案解析：Vue2基于Object.defineProperty劫持属性读写，结合发布订阅模式实现数据更新视图、视图修改同步数据；Vue3基于Proxy代理整个对象，支持数组、新增属性监听，解决Vue2数据监听缺陷。</p>', 1, 11, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Vue生命周期及常用钩子？</p>', '<p>答案解析：核心生命周期：创建、挂载、更新、销毁。常用钩子：created（获取数据）、mounted（DOM挂载完成、操作DOM）、updated（数据更新）、beforeUnmount（销毁前清理定时器、监听）。</p>', 1, 11, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>computed与watch区别？</p>', '<p>答案解析：computed：计算属性、有缓存、依赖值变化才更新、适合数据计算；watch：监听属性、无缓存、数据变化立即触发、适合异步操作、复杂业务监听。</p>', 1, 11, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Vue组件通信常用方式？</p>', '<p>答案解析：父子通信：props、$emit、$parent/$children；跨级通信：provide/inject；全局通信：Vuex/Pinia、全局事件总线；兄弟通信：状态管理、事件总线。</p>', 1, 11, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Vuex核心模块与作用？</p>', '<p>答案解析：state（全局状态数据）、mutations（同步修改状态）、actions（异步操作、调用mutations）、getters（数据计算过滤）、modules（模块化拆分状态），实现全局数据统一管理。</p>', 1, 11, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Vue路由守卫作用与分类？</p>', '<p>答案解析：路由守卫用于权限控制、页面拦截、登录校验。分为：全局守卫、路由独享守卫、组件内守卫，可拦截未登录访问、权限不足页面、控制页面跳转逻辑。</p>', 1, 11, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>路由懒加载原理与作用？</p>', '<p>答案解析：动态导入组件，访问对应路由才加载组件JS文件，首屏只加载核心代码，减少首屏加载体积、提升页面初始化速度、优化项目性能。</p>', 1, 11, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Vue key属性作用？</p>', '<p>答案解析：列表渲染key唯一标识节点，帮助Vue diff算法精准对比新旧节点，减少DOM误更新、提升渲染性能，禁止使用index作为key，易出现数据错乱问题。</p>', 1, 11, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Vue diff算法核心原理？</p>', '<p>答案解析：虚拟DOM对比算法，同层对比、不跨层级比对，通过key精准匹配节点，最小化DOM操作，批量更新页面，大幅提升页面渲染效率，是Vue高性能渲染核心。</p>', 1, 11, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>v-if与v-show区别？</p>', '<p>答案解析：v-if：动态创建/销毁DOM节点、切换开销大、初始渲染开销小；v-show：CSS切换显示隐藏、DOM常驻、切换开销小、初始开销大。频繁切换用v-show，极少切换用v-if。</p>', 1, 11, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Vue自定义指令作用与场景？</p>', '<p>答案解析：封装通用DOM操作逻辑，全局复用。常用场景：按钮权限、防抖节流、复制文本、图片懒加载、输入框聚焦，减少重复代码，统一业务规范。</p>', 1, 11, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Vue组件封装原则？</p>', '<p>答案解析：单一职责、高内聚低耦合、props校验、事件解耦、样式隔离、通用逻辑抽离，封装可复用公共组件，提升项目开发效率、统一UI风格。</p>', 1, 11, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>setup语法糖优势？</p>', '<p>答案解析：Vue3简化语法，无需return变量、无需定义setup函数、代码更简洁、支持TS更友好、属性方法自动暴露，是目前Vue3项目主流写法。</p>', 1, 11, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>ref与reactive区别？</p>', '<p>答案解析：ref：适配基本类型、简单对象，通过.value取值；reactive：适配复杂对象、数组，无需.value，针对性区分使用场景，规范响应式数据定义。</p>', 1, 11, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Vue路由跳转方式与参数传递？</p>', '<p>答案解析：声明式跳转：router-link标签；编程式跳转：$router.push。参数传递：params动态参数、query拼接参数，params参数隐式传递、query参数地址栏可见。</p>', 1, 11, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Vue跨域解决方案？</p>', '<p>答案解析：开发环境：vue.config.js配置代理转发，拦截前端请求转发后端接口；生产环境：Nginx反向代理、后端配置跨域放行，彻底解决前后端跨域问题。</p>', 1, 11, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Vue性能优化常用手段？</p>', '<p>答案解析：路由懒加载、组件按需引入、图片懒加载、节流防抖、缓存计算属性、长列表虚拟滚动、打包压缩、去除冗余依赖、避免频繁DOM操作。</p>', 1, 11, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>Pinia相比Vuex优势？</p>', '<p>答案解析：无需mutations、语法更简洁、TS支持友好、模块化天然隔离、无嵌套结构、体积更小、使用更灵活，是Vue3官方推荐状态管理工具。</p>', 1, 11, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>前端页面白屏、卡顿优化方案？</p>', '<p>答案解析：首屏加载优化、资源压缩、懒加载、骨架屏、减少无效渲染、避免死循环、优化长列表、分离大型计算逻辑、异步拆分任务，提升页面加载与交互体验。</p>', 1, 11, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>项目中如何解决接口超时、重试问题？</p>', '<p>答案解析：基于拦截器统一配置超时时间，自定义重试机制，针对幂等接口失败自动重试，非幂等接口禁止重试；配合熔断降级，超时次数过多触发熔断，保护服务稳定性。</p>', 1, 12, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>线上OOM内存泄漏排查实战流程？</p>', '<p>答案解析：监控发现内存持续上涨→导出heapdump快照→MAT分析大对象、常驻对象→定位未释放资源（集合未清空、ThreadLocal未移除、静态集合堆积）→代码修复、压测验证。</p>', 1, 12, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>项目中如何实现接口限流？</p>', '<p>答案解析：网关层全局限流（Sentinel）、接口粒度QPS限流、IP限流、用户维度限流，超出阈值直接返回兜底提示，防止瞬时流量压垮后端服务，保障系统平稳运行。</p>', 1, 12, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>分布式ID生成方案选型与实战？</p>', '<p>答案解析：项目主流：雪花算法（有序、高性能）、Redis自增、数据库号段模式。雪花算法适配绝大多数业务，解决自增ID单调、不安全、分库分表ID冲突问题。</p>', 1, 12, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>高并发秒杀项目核心解决方案？</p>', '<p>答案解析：前端限流、按钮防抖、Redis预减库存、消息队列异步下单、接口防刷、分布式锁、库存兜底校验、秒杀结果异步通知，削峰填谷、避免超卖、支撑高并发流量。</p>', 1, 12, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>项目超卖问题如何彻底解决？</p>', '<p>答案解析：数据库乐观锁版本号更新、Redis原子扣减库存、Lua脚本保证扣减原子性、最终数据库校验兜底，多层防护彻底杜绝商品超卖问题。</p>', 1, 12, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>线上慢SQL优化实战流程？</p>', '<p>答案解析：开启慢查询日志→定位Top慢SQL→explain分析执行计划→优化索引、改写SQL、避免索引失效→压测验证性能→上线观察监控、持续优化。</p>', 1, 12, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>缓存雪崩线上应急处理与预防？</p>', '<p>答案解析：应急：临时扩容Redis、接口熔断降级、临时兜底数据；预防：过期时间随机打散、Redis集群高可用、永久热点Key、多级缓存，规避批量过期雪崩风险。</p>', 1, 12, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>项目中如何保证接口幂等？</p>', '<p>答案解析：统一基于唯一流水号+Redis校验，新增/支付/订单接口强制幂等，拦截重复请求；结合数据库唯一索引、状态机二次校验，彻底解决重复提交、重复扣款问题。</p>', 1, 12, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>微服务跨服务调用异常排查实战？</p>', '<p>答案解析：查看链路追踪日志→定位异常服务节点→排查超时、熔断、参数异常→核对注册中心实例状态→检查网络、配置、权限→修复重试、补充兜底逻辑。</p>', 1, 12, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>大文件、大数据量导出优化方案？</p>', '<p>答案解析：禁止一次性加载全量数据，采用分页查询、流式写入、异步导出、文件临时存储、前端分片下载，避免内存溢出、接口超时，适配十万级、百万级数据导出。</p>', 1, 12, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>项目权限系统设计思路？</p>', '<p>答案解析：基于RBAC角色权限模型，用户-角色-资源三级关联，网关统一鉴权、接口权限校验、按钮级权限控制，支持动态权限配置、权限刷新，适配后台管理系统。</p>', 1, 12, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>登录认证JWT+Redis实战方案？</p>', '<p>答案解析：登录生成JWT令牌、Redis存储用户权限信息、过期自动失效；拦截器校验令牌合法性、有效性，支持单点登录、踢下线、刷新令牌，无状态认证、适配分布式集群。</p>', 1, 12, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>项目日志规范与线上排查技巧？</p>', '<p>答案解析：统一日志格式、打印链路ID、分级日志（info/error/warn）、禁止打印敏感信息；线上通过链路ID串联全链路日志，快速定位异常堆栈、请求参数、报错点位。</p>', 1, 12, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>定时任务项目实战与避免重复执行？</p>', '<p>答案解析：基于XXL-JOB分布式定时任务，替代原生定时任务；通过任务锁、分片策略、执行状态记录，防止集群多实例重复执行、任务堆积、任务超时问题。</p>', 1, 12, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>项目安全防护方案？</p>', '<p>答案解析：防SQL注入、XSS跨站、CSRF跨域伪造、接口防刷、密码加密存储、敏感数据脱敏、接口权限校验、日志脱敏、防止越权访问，全方位保障项目安全。</p>', 1, 12, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>分库分表实战落地注意事项？</p>', '<p>答案解析：合理选择分片键、避免跨库跨表关联、提前规划扩容、兼容旧数据、分批迁移、双写过渡、灰度上线，规避分片热点、数据倾斜、查询复杂问题。</p>', 1, 12, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>项目高并发优化整体思路？</p>', '<p>答案解析：前端防抖限流+网关防护+缓存优化+异步削峰+数据库优化+集群扩容+熔断降级+故障隔离，层层防护、逐级优化，提升系统并发承载能力。</p>', 1, 12, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>线上故障复盘流程？</p>', '<p>答案解析：记录故障现象、影响范围、发生时间→定位根因→临时恢复预案→永久代码修复→补充监控告警、优化机制、沉淀经验，避免同类问题重复发生。</p>', 1, 12, 0, 0, NULL, CURRENT_TIMESTAMP),
  ('<p>项目难点与亮点面试通用总结？</p>', '<p>答案解析：难点：高并发流量管控、分布式事务一致性、海量数据查询优化、线上故障排查；亮点：自研幂等框架、多级缓存架构、异步削峰设计、全链路监控、性能优化提升QPS、降低故障率，提升系统稳定性与承载能力。</p><p>|（注：部分内容可能由 AI 生成）</p>', 1, 12, 0, 0, NULL, CURRENT_TIMESTAMP);